version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: jaffslomos_db
    environment:
      POSTGRES_USER: jaffs_admin
      POSTGRES_PASSWORD: jaffs_password_123 # Contraseña local de prueba
      POSTGRES_DB: jaffslomos
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
